export const ingredientsSuggesions = [
  'apple',
  'banana',
  'blueberry',
  'broccoli',
  'carrot',
  'cauliflower',
  'celery',
  'chicken',
  'chickpeas',
  'cucumber',
  'egg',
  'eggplant',
  'flour',
  'garlic',
  'ginger',
  'lettuce',
  'mushroom',
  'onion',
  'orange',
  'potato',
  'spinach',
  'tomato',
  'zucchini',
  'beef',
  'pork',
  'lamb',
  'tofu',
  'turkey',
  'fish',
  'shrimp',
  'milk',
  'butter',
  'cheddar cheese',
  'cream cheese',
  'feta cheese',
  'mozzarella',
  'parmesan',
  'ricotta',
  'yogurt',
  'olive oil',
  'vegetable oil',
  'baking powder',
  'baking soda',
  'brown sugar',
  'granulated sugar',
  'honey',
  'salt',
  'black pepper',
  'vinegar',
  'soy sauce',
  'mustard',
  'ketchup',
  'cornstarch',
  'rice',
  'pasta',
  'quinoa',
  'oats',
  'bread',
  'tortilla',
  'crackers',
  'nuts',
  'almonds',
  'walnuts',
  'pecans',
  'peanut butter',
  'coconut milk',
  'chocolate',
  'cocoa powder',
  'vanilla extract',
  'fresh herbs',
  'basil',
  'parsley',
  'cilantro',
  'thyme',
  'rosemary',
  'sage',
  'chives',
  'bell pepper',
  'sweet potato',
  'radish',
  'turnip',
  'asparagus',
  'green beans',
  'peas',
  'corn',
  'cabbage',
  'kale',
  'arugula',
  'fruit juice',
  'maple syrup',
  'agave syrup',
  'tapioca',
  'semolina',
  'bulgur',
  'farro',
  'millet',
  'barley',
  'couscous',
  'canned tomatoes',
  'canned beans',
  'canned corn',
  'chicken broth',
  'vegetable broth',
  'seafood',
  'salami',
  'ham',
  'bacon',
  'sour cream',
  'cream',
  'heavy cream',
  'whipping cream',
  'gelatin',
  'salsa',
  'marshmallows',
  'jelly',
  'pickles',
  'kimchi',
  'sauerkraut',
  'miso',
  'seaweed',
  'dried fruits',
  'raisins',
  'cranberries',
  'dates',
  'figs',
  'coconut flakes',
  'nut milk',
  'almond milk',
  'oat milk',
  'soy milk',
  'coconut yogurt',
  'nutritional yeast',
  'tempeh',
  'seitan',
  'textured vegetable protein',
  'instant noodles',
  'potato chips',
  'popcorn',
  'frozen vegetables',
  'frozen fruits',
  'fruit snacks',
  'edamame',
  'hummus',
  'pesto',
  'curry paste',
  'balsamic vinegar',
  'red wine vinegar',
  'white wine vinegar',
  'coconut oil',
  'shortening',
  'lard',
  'sugar substitute',
  'flax seeds',
  'chia seeds',
  'cocoa nibs',
  'nut butter',
  'baby spinach',
  'broccoli rabe',
  'fennel',
  'leeks',
  'shallots',
  'scallions',
  'beet',
  'butternut squash',
  'acorn squash',
  'egg noodles',
  'chocolate chips',
  'ice cream',
  'tortilla chips',
  'coconut cream',
  'pearl couscous',
  'golden raisins',
  'saffron',
  'pepper jack cheese',
  'goat cheese',
  'vegan cheese',
  'quail eggs',
  'duck eggs',
  'sunflower seeds',
  'pumpkin seeds',
  'wild rice',
  'arborio rice',
  'canned pumpkin',
  'sweetened condensed milk',
  'coconut milk powder',
  'dried herbs',
  'cumin',
  'paprika',
  'coriander',
  'cardamom',
  'nutmeg',
  'vanilla bean',
  'zest of lemon',
  'zest of orange',
  'fresh fruit',
  'frozen fruit',
  'fruit preserves',
  'baking chocolate',
  "confectioners' sugar",
  'light brown sugar',
  'white sugar',
  'sweet soy sauce',
  'stevia',
  'xylitol',
  'chocolate syrup',
  'barbecue sauce',
  'marinara sauce',
  'teriyaki sauce',
  'taco seasoning',
  'ranch dressing',
  'italian dressing',
  'hot sauce',
  'chili sauce',
  'buffalo sauce',
  'mayo',
  'aioli',
  'tartar sauce',
  'horseradish',
  'dijon mustard',
  'yellow mustard',
  'cake mix',
  'cookie mix',
  'instant pudding mix',
  'potato flakes',
  'instant rice',
  'puffed rice',
  'croutons',
  'granola',
  'cereal',
  'granola bars',
  'cheese powder',
  'beef stock',
  'vegetable stock',
  'chicken stock',
  'clam',
  'crab',
  'lobster',
  'oyster',
  'canned fruit',
  'canned soup',
  'pasta sauce',
  'fish sauce',
  'sriracha',
  'tomato paste',
  'pasta salad',
  'pita bread',
  'whole wheat flour',
  'cake flour',
  'self-rising flour',
  'potato flour',
  'coconut flour',
  'chickpea flour',
  'rice flour',
  'all-purpose flour',
  'granulated garlic',
  'dried oregano',
  'curry powder',
  'seasoned salt',
  'sea salt',
  'kosher salt',
  'vegetable shortening',
  'buttermilk',
  'heavy whipping cream',
  'evaporated milk',
  'apple cider vinegar',
  'lime juice',
  'orange juice',
  'coconut sugar',
  'mango',
  'pineapple',
  'papaya',
  'pomegranate',
  'kiwi',
  'blackberries',
  'raspberries',
  'cantaloupe',
  'honeydew melon',
  'nectarine',
  'green onion',
  'radicchio',
  'snap peas',
  'sugar snap peas',
  'baby carrots',
  'chili pepper',
  'squash',
  'sweet bell pepper',
  'canned artichokes',
  'sun-dried tomatoes',
  'canned olives',
  'green olives',
  'black olives',
  'pimiento',
  'capers',
  'sesame oil',
  'peanut oil',
  'canola oil',
  'corn oil',
  'white vinegar',
  'cider vinegar',
  'fish stock',
  'miso paste',
  'rice vinegar',
  'hollandaise sauce',
  'tomatillos',
  'mushroom broth',
  'pasta shells',
  'lasagna noodles',
  'whole grain pasta',
  'green lentils',
  'red lentils',
  'black beans',
  'kidney beans',
  'pinto beans',
  'oat flour',
  'sweet potato flour',
  'quinoa flour',
  'spelt flour',
  'barley flour',
  'teff flour',
  'buckwheat flour',
  'dried beans',
  'canned chili',
  'stuffed olives',
  'grape leaves',
  'soba noodles',
  'udon noodles',
  'rice noodles',
  'pea protein',
  'chickpea pasta',
  'cereal',
  'protein powder',
  'dietary supplements',
  'chervil',
  'dried parsley',
  'dried thyme',
  'dried dill',
  'dried basil',
  'dried cilantro',
  'dried chives',
  'dried rosemary',
]
  .map((value) => ({ value, sort: Math.random() }))
  .sort((a, b) => a.sort - b.sort)
  .map(({ value }) => value.toLowerCase())
