export const ingredientsSuggesions = [
  'almonds',
  'apple',
  'apricots',
  'artichokes',
  'asparagus',
  'avocado',
  'bacon',
  'balsamic vinegar',
  'banana',
  'barley',
  'beef',
  'beets',
  'bell peppers',
  'black beans',
  'blueberries',
  'bok choy',
  'broccoli',
  'brown rice',
  'butter',
  'cabbage',
  'cantaloupe',
  'carrots',
  'cauliflower',
  'celery',
  'cheddar cheese',
  'chicken',
  'chickpeas',
  'chocolate',
  'coconut milk',
  'corn',
  'cottage cheese',
  'cucumber',
  'dates',
  'eggplant',
  'eggs',
  'feta cheese',
  'figs',
  'flour',
  'frozen peas',
  'garlic',
  'ginger',
  'goat cheese',
  'grapes',
  'green beans',
  'green onions',
  'honey',
  'jalapeños',
  'kale',
  'kiwi',
  'lamb',
  'leeks',
  'lemons',
  'limes',
  'mango',
  'melons',
  'milk',
  'mushrooms',
  'navy beans',
  'nectarines',
  'oats',
  'olive oil',
  'onions',
  'oranges',
  'oysters',
  'parmesan cheese',
  'peaches',
  'peanuts',
  'pears',
  'peas',
  'pepper jack cheese',
  'pineapple',
  'pistachios',
  'potatoes',
  'pumpkin',
  'quinoa',
  'radishes',
  'raspberries',
  'rice',
  'salmon',
  'sardines',
  'shrimp',
  'spinach',
  'squash',
  'steak',
  'strawberries',
  'sugar',
  'sweet potatoes',
  'tofu',
  'tomatoes',
  'turkey',
  'walnuts',
  'watermelon',
  'zucchini',
  'arugula',
  'basil',
  'bok choy',
  'broccolini',
  'cabbage',
  'carambola',
  'cayote',
  'cress',
  'dandelion greens',
  'endive',
  'fennel',
  'frisée',
  'kohlrabi',
  'mache',
  'mizuna',
  'mustard greens',
  'nopales',
  'radicchio',
  'rapini',
  'savoy cabbage',
  'seaweed',
  'sorrel',
  'tatsoi',
  'turnips',
  'watercress',
  'yuca',
  'chard',
  'collard greens',
  'curry leaves',
  'mint',
  'parsley',
  'thyme',
  'cilantro',
  'dill',
  'sage',
  'rosemary',
  'tarragon',
  'chives',
  'bay leaves',
  'fennel seeds',
  'coriander',
  'cumin',
  'caraway',
  'fenugreek',
  'nutmeg',
  'allspice',
  'cinnamon',
  'vanilla',
  'buttermilk',
  'coconut',
  'egg noodles',
  'tortillas',
  'baguette',
  'pasta',
  'polenta',
  'quiche',
  'sourdough',
  'spelt',
  'cornmeal',
  'rice noodles',
  'semolina',
  'pita',
  'crepes',
  'wheat flour',
  'cake flour',
  'pastry flour',
  'honey',
  'maple syrup',
  'agave nectar',
  'cane sugar',
  'brown sugar',
  "confectioners' sugar",
  'corn syrup',
  'sweetened condensed milk',
  'evaporated milk',
  'sour cream',
  'cream cheese',
  'greek yogurt',
  'mayonnaise',
  'ketchup',
  'mustard',
  'hot sauce',
  'soy sauce',
  'teriyaki sauce',
  'fish sauce',
  'tamarind',
  'vinegar',
  'rice vinegar',
  'white wine',
  'red wine',
  'cooking wine',
  'stock',
  'chicken stock',
  'beef stock',
  'vegetable stock',
  'bone broth',
  'coconut cream',
  'peanut butter',
  'almond butter',
  'sunflower seed butter',
  'hazelnut spread',
  'gelatin',
  'pectin',
  'cooking spray',
  'shortening',
  'crisco',
  'ghee',
  'olive paste',
  'tapenade',
  'salsa',
  'relish',
  'miso',
  'kimchi',
  'couscous',
  'farro',
  'dry beans',
  'dry lentils',
  'dry peas',
  'nori',
  'rice paper',
  'tempura batter',
  'wonton wrappers',
  'egg roll wrappers',
  'baking powder',
  'baking soda',
  'yeast',
  'vanilla extract',
  'almond extract',
  'coconut extract',
  'food coloring',
  'flavored salts',
  'fruit preserves',
  'jelly',
  'jam',
  'marshmallows',
  'meringue',
  'biscuits',
  'croissants',
  'puff pastry',
  'phyllo dough',
  'ganache',
  'frosting',
  'fondant',
  'chocolate chips',
  'baking chocolate',
  'cacao powder',
  'carob',
  'nut butters',
  'potato chips',
  'crisps',
  'crackers',
  'nuts',
  'dried fruit',
  'trail mix',
  'granola',
  'cereal',
  'oatmeal',
  'frozen vegetables',
  'frozen fruit',
  'dried herbs',
  'arborio rice',
  'wild rice',
  'sushi rice',
  'sticky rice',
  'farro',
  'quinoa',
  'bulgur',
  'millet',
  'spelt',
  'chickpea flour',
  'soy flour',
  'rice flour',
  'potato flour',
  'tapioca',
  'arrowroot',
  'coconut flour',
  'cake mix',
  'baking mixes',
  'sourdough starter',
  'cream of tartar',
  'pudding mix',
  'cornstarch',
  'gelato',
  'sorbet',
  'ice cream',
  'frozen yogurt',
  'cheesecake',
  'butterscotch',
  'custard',
  'creme brulee',
  'fruit toppings',
  'dessert toppings',
  'pasta sauce',
  'pizza sauce',
  'barbecue sauce',
  'hot pepper sauce',
  'fruit juice',
  'vegetable juice',
  'nut milk',
  'soy milk',
  'almond milk',
  'coconut yogurt',
  'plant-based cheese',
  'nutritional yeast',
  'seitan',
  'tempeh',
  'edamame',
  'hearts of palm',
  'jackfruit',
  'sauerkraut',
  'fermented vegetables',
  'pickled vegetables',
  'capers',
  'sundried tomatoes',
  'marinated olives',
  'canned artichokes',
  'canned mushrooms',
  'canned beans',
  'canned tomatoes',
  'canned corn',
  'canned fruit',
  'canned soup',
  'fish fillets',
  'prawns',
  'cooked ham',
  'bologna',
  'salami',
  'pepperoni',
  'hot dogs',
  'tuna',
  'mackerel',
  'crab',
  'lobster',
  'clams',
  'mussels',
  'cod',
  'tilapia',
  'trout',
  'catfish',
  'flounder',
  'halibut',
  'frozen seafood',
  'pork loin',
  'bacon bits',
  'liver',
  'ground turkey',
  'ground chicken',
  'ground beef',
  'lamb chops',
  'beef brisket',
  'pork chops',
  'venison',
  'rabbit',
  'game meat',
  'smoked salmon',
  'canned tuna',
  'smoked mackerel',
  'canned sardines',
  'anchovies',
  'fresh herbs',
  'baby spinach',
  'baby arugula',
  'mushroom varieties',
  'black-eyed peas',
  'kidney beans',
  'pinto beans',
  'cannellini beans',
  'fava beans',
  'white beans',
  'edible flowers',
  'sea vegetables',
  'cacao nibs',
  'coconut flakes',
  'dried seaweed',
  'cooking wine',
  'fermented soy products',
  'almond milk powder',
]
  .map((value) => ({ value, sort: Math.random() }))
  .sort((a, b) => a.sort - b.sort)
  .map(({ value }) => value)
